format = """
[  ](fg:#a3aed2) \
$hostname\
$directory\
$localip\
$dotnet $golang $python $container $nodejs $nix_shell $lua\
$fill\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration $jobs $time\
$line_break\
$container\
$character"""

palette = "catppuccin_mocha"


[fill]
symbol = " "

[directory]
read_only = " 󰌾"
style = "#7dcfff"
format = '[\[$path\]]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = " "

[character]
success_symbol = "[❯](#7aa2f7)"
error_symbol = "[❯](#f7768e)"
vicmd_symbol = "[❮](#9ece6a)"

[git_branch]
symbol = "  "
format = '[$symbol\[$branch\]]($style)'
style = "fg:769ff0"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#73daca"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#bb9af7"

[git_metrics]
disabled = false

[jobs]
symbol = ""
style = "#f7768e"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "#e0af68"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[nodejs]
symbol = '󰎙'
style = '#9ece6a'
format = "via [$symbol($version )]($style)"

[golang]
symbol = '󰟓 '
style = "#b4f9f8"
format = 'via [$symbol($version )($mod_version )]($style)'

[container]
symbol = '⬢'
format = '[$symbol \[$name\]]($style) '

[dotnet]
symbol = ' '
style = 'bold fg:#7aa2f7'
heuristic = true
version_format = 'v${raw}'
format = ' [${symbol}dotnet (${version} )(\($tfm\))]($style)'
detect_extensions = ["sln", "cs"]

[localip]
ssh_only = false
format = '[\[$localipv4\]](red)'
disabled = false

[nix_shell]
symbol= '󱄅 '
disabled = false
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [󱄅 $state( \($name\))](#7dcfff) '

[lua]
format = 'via [$symbol($version )]($style)'
symbol = ''
detect_extensions = ['lua']

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"
