format = """
[  ](fg:aqua) \
$hostname\
$directory\
$localip\
$dotnet $golang $python $container $nodejs $nix_shell $lua\
$fill\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration $jobs $time\
$line_break\
$container\
$character"""

palette = "everforest"


[fill]
symbol = " "

[directory]
read_only = " 󰌾"
style = "fg"
format = '[\[$path\]]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = " "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](#9ece6a)"

[git_branch]
symbol = "  "
format = '[$symbol\[$branch\]]($style)'
style = "fg:yellow"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "green"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "purple"

[git_metrics]
disabled = false

[jobs]
symbol = ""
style = "grey2"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "#orange"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:bg0"
format = '[[  $time ](fg:grey0)]($style)'

[nodejs]
symbol = '󰎙'
style = 'green'
format = "via [$symbol($version )]($style)"

[golang]
symbol = '󰟓 '
style = "aqua"
format = 'via [$symbol($version )($mod_version )]($style)'

[container]
symbol = '⬢'
format = '[$symbol \[$name\]]($style) '

[dotnet]
symbol = ' '
style = 'bold fg:purple'
heuristic = true
version_format = 'v${raw}'
format = ' [${symbol}dotnet (${version} )(\($tfm\))]($style)'
detect_extensions = ["sln", "cs"]

[localip]
ssh_only = false
format = '[\[$localipv4\]](red)'
disabled = false

[nix_shell]
symbol= '󱄅 '
disabled = false
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [󱄅 $state( \($name\))](blue) '

[lua]
style = 'bold fg:aqua'
format = 'via [$symbol($version )]($style)'
symbol = ''
detect_extensions = ['lua']

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"


[palettes.everforest]
bg_dim = "#232a2e"
bg0 = "#2d353b"
bg1 = "#343f44"
bg2 = "#3d484d"
bg3 = "#475258"
bg4 = "#4f585e"
bg5 = "#56635f"
bg_visual = "#543a48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3a515d"
bg_yellow = "#4d4c43"
fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"
